# Plugins:
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# Site Settings:
repository: "AbdulrahmanMohammadSalem/AbdulrahmanMohammadSalem.github.io"
url: "https://abdulrahmanmohammadsalem.github.io"
baseurl: ""
github_username: AbdulrahmanMohammadSalem
locale: "en"
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"

compress_html:
  clippings: all
  ignore:
    envs: development

# Site Title:
title: Salem's Projects Portofolio
title_separator: "|"
description: "A GitHub Pages site showcasing Abdulrahman Mohammad Salem's software development work."

# Header:
masthead_title: "Abdulrahman Mohammad Salem"
subtitle: "C++/.NET Framework Junior Developer"
logo: "/assets/images/My Photo.jpg"

# Body:
highlighter: rouge
enable_copy_code_button: true

collections:
  CppConsoleApps:
    output: true
    permalink: /:collection/:path/
  CppLibs:
    output: true
    permalink: /:collection/:path/
  CppClasses:
    output: true
    permalink: /:collection/:path/
  CsWinFormsApps:
    output: true
    permalink: /:collection/:path/
  
defaults:
  - scope: # For all pages in the website
      path: ""
    values:
      author_profile: false
      toc: true
      toc_label: "Table of Contents"
      toc_sticky: true
      sidebar:
        nav: "side_nav"
  - scope: # For all pages directly in the root
      path: ""
      type: "pages"
    values:
      classes: wide # This will override the toc in those pages
  - scope: # For CppConsoleApps
      path: ""
      type: "CppConsoleApps"
    values:
      layout: single
      header:
        teaser: /assets/images/thumbnails/prev_ConsoleApps.jpg
      css_properties:
        border_radius: 10px
        top: 56%
        left: 50%
  - scope: # For CppLibs
      path: ""
      type: "CppLibs"
    values:
      layout: single
      header:
        teaser: /assets/images/thumbnails/prev_CppLibs.jpg
    css_properties:
        border_radius: 17px
        top: 50%
        left: 50%
  - scope: # For CppClasses
      path: ""
      type: "CppClasses"
    values:
      layout: single
      header:
        teaser: /assets/images/thumbnails/prev_CppClasses.jpg
      css_properties:
        border_radius: 17px
        top: 50%
        left: 50%  
  - scope: # For CsWinFormsApps
      path: ""
      type: "CsWinFormsApps"
    values:
      layout: single
      header:
        teaser: /assets/images/thumbnails/prev_CsWinFormsApps.jpg      
      css_properties:
        border_radius: 12px
        border: "4px solid #0000004a"
        overlay_text_color: "#4c4c4c"
        top: 54%
        left: 62%

# Footer:
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AbdulrahmanMohammadSalem/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/abdulrahman-salem-257672365/"
    - label: "YouTube"  
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@AbdulrahmanMohammadSalem"
    - label: "Email"
      icon: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&to=abdulrahmansalem.contact@gmail.com"  
      
atom_feed:
    path: ""
    hide: true
